# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

def swinject_pods
    pod 'Swinject', '2.0.0'
    pod 'SwinjectStoryboard', '1.0.0'
end

target 'TV Show Calendar' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.0'
  pod 'SwiftyJSON', '~> 3.1'
  swinject_pods
  # Pods for TV Show Calendar
  
end
