# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'TV Show Calendar' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.0'
  pod 'SwiftyJSON','~> 3.1'
  pod 'RxSwift',   '~> 3.0'
  pod 'Kingfisher', '~> 3.0'
  pod 'SVProgressHUD'
  # Pods for TV Show Calendar
  
end
